// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetTokens():Promise<backend.LoginResponse>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function SendOtp(arg1:string):Promise<void>;
