// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTokens() {
  return window['go']['backend']['AuthBridge']['GetTokens']();
}

export function Login(arg1, arg2) {
  return window['go']['backend']['AuthBridge']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['backend']['AuthBridge']['Logout']();
}

export function SendOtp(arg1) {
  return window['go']['backend']['AuthBridge']['SendOtp'](arg1);
}
